---
sudo: required
language: python
services: docker

env:
  - version=">=2.6,<2.7" distro="alpine-latest"
  - version="" distro="alpine-latest"
  - version="devel" distro="alpine-latest"
  - version=">=2.6,<2.7" distro="alpine-edge"
  - version="" distro="alpine-edge"
  - version="devel" distro="alpine-edge"
  - version=">=2.6,<2.7" distro="archlinux"
  - version="" distro="archlinux"
  - version="devel" distro="archlinux"
  - version=">=2.6,<2.7" distro="centos-6"
  - version="" distro="centos-6"
  - version="devel" distro="centos-6"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.6,<2.7" distro="debian-latest"
  - version="" distro="debian-latest"
  - version="devel" distro="debian-latest"
  - version=">=2.6,<2.7" distro="debian-stable"
  - version="" distro="debian-stable"
  - version="devel" distro="debian-stable"
  - version=">=2.6,<2.7" distro="debian-unstable"
  - version="" distro="debian-unstable"
  - version="devel" distro="debian-unstable"
  - version=">=2.6,<2.7" distro="fedora-latest"
  - version="" distro="fedora-latest"
  - version="devel" distro="fedora-latest"
  - version=">=2.6,<2.7" distro="fedora-rawhide"
  - version="" distro="fedora-rawhide"
  - version="devel" distro="fedora-rawhide"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version="" distro="opensuse-leap"
  - version="devel" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed"
  - version="" distro="opensuse-tumbleweed"
  - version="devel" distro="opensuse-tumbleweed"
  - version=">=2.6,<2.7" distro="ubuntu-artful"
  - version="" distro="ubuntu-artful"
  - version="devel" distro="ubuntu-artful"
  - version=">=2.6,<2.7" distro="ubuntu-latest"
  - version="" distro="ubuntu-latest"
  - version="devel" distro="ubuntu-latest"
  - version=">=2.6,<2.7" distro="ubuntu-devel"
  - version="" distro="ubuntu-devel"
  - version="devel" distro="ubuntu-devel"

matrix:
  fast_finish: yes
  allow_failures:
    - env: version=">=2.6,<2.7" distro="alpine-edge"
    - env: version="" distro="alpine-edge"
    - env: version="devel" distro="alpine-edge"
    - env: version="devel" distro="alpine-latest"
    - env: version="devel" distro="archlinux"
    - env: version="devel" distro="centos-6"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-latest"
    - env: version="devel" distro="debian-stable"
    - env: version=">=2.6,<2.7" distro="debian-unstable"
    - env: version="" distro="debian-unstable"
    - env: version="devel" distro="debian-unstable"
    - env: version="devel" distro="fedora-latest"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide"
    - env: version="" distro="fedora-rawhide"
    - env: version="devel" distro="fedora-rawhide"
    - env: version="devel" distro="opensuse-leap"
    - env: version="devel" distro="opensuse-tumbleweed"
    - env: version="devel" distro="ubuntu-artful"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel"
    - env: version="" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-devel"
    - env: version="devel" distro="ubuntu-latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "LgFNChn6NXhUm4cK8eOH1NG4SdLpiTbmh6e1XbUw4QfUHGxbG+0tlRN3ygrWlQE9uisV19dYvyPvVvwbMkxSJJItoPmaiuXopKPA4sANGsQCLGU3CYgL3A+3HmP0geTQtyqg/RxnzqTAxozP6DaM/z2P7j6KVz2TB7eaaHjGaq9iSlNmdJmwshkOfmkZccko9vTPOFZ3mDV0DKR13ALKJFzlSrb9KnilennQD0jNh8KUQ2neqMcrCtXDVLP3pfer0qgb6G8kcW0vFe5L6SW7iFyMyaceQJDk+8jobIaECrOsz6plz11O/npG4vyLSwq1ZxZJkJUZJoIPSZ4UNpkXZBIZRRguy7hhnGjxN70Zitg/r0f93R/6m/NAubAdTYV1wqKnPeiQ/GLeypbKP5NpCjndAqf0rkKCwZd9dy7VV7RL3CJIYwCQepy1/vJNFhaPC1X/Sr8tkf1Md2Yet29g7ts2ZR5zRcgG5UOKWNu2F20NnwDJJX8KZBzhQkLBFK7Ck/t4NxZDHXCVXKsu24yZGWyoWd44WSbDjE72xBR+TggT/2pTxGaTUJ7DHJS4yb7T/4ZmSIM7xnPWlzr0E+kFh3dmsG5+sYH5nSxpfw/S+NPxaZNwMSmTB6yVYm9LZWN0RNGa1ZCjdjMk1oOSXmXK9xb/8tDU/xgC2OU+M2Bqrpk="
  email: false
