---
# tasks file for lynis
- name: install lynis
  git:
    repo: "{{ lyris_repository }}"
    dest: "{{ lyris_destination }}"
    version: "{{ lyris_version }}"

- name: audit system
  shell: "{{ lyris_destination }}/lynis audit system | tee -a {{ lyris_output }}"
  register: audit_system
  args:
    creates: "{{ lyris_output }}"
    chdir: "{{ lyris_destination }}"
  when:
    - lyris_run_now

- name: schedule a run of lyris
  cron:
    name: run lyris
    minute: "23"
    hour: "4"
    job: "{{ lyris_destination }}/lynis --cronjob audit system | tee -a {{ lyris_output }}"
    file: lyris
    user: root
  when:
    - lyris_cronjob
    - ansible_virtualization_type != "docker" or lyris_ignore_docker
